import { v } from "convex/values"
import { mutation, query } from "./_generated/server"
import { getAuthUserId } from "@convex-dev/auth/server"
async function uid(ctx:any){const id=await getAuthUserId(ctx);if(!id)throw new Error("Authentication required");return String(id)}
export const dashboard=query({args:{},handler:async(ctx)=>{const userId=await uid(ctx);const [profile,plans,assignments,progress,groups,scholarships]=await Promise.all([ctx.db.query("profiles").withIndex("by_user",q=>q.eq("userId",userId)).first(),ctx.db.query("studyPlans").withIndex("by_user_date",q=>q.eq("userId",userId)).take(20),ctx.db.query("assignments").withIndex("by_user",q=>q.eq("userId",userId)).take(20),ctx.db.query("progress").withIndex("by_user",q=>q.eq("userId",userId)).take(20),ctx.db.query("groups").withIndex("by_owner",q=>q.eq("ownerId",userId)).take(20),ctx.db.query("scholarships").withIndex("by_user",q=>q.eq("userId",userId)).take(20)]);return {profile,plans,assignments,progress,groups,scholarships}}})
export const saveProfile=mutation({args:{name:v.string(),country:v.string(),educationLevel:v.string(),school:v.string(),subjects:v.array(v.string()),preferredLanguage:v.string(),timeZone:v.string(),goal:v.string(),upcomingExams:v.array(v.string()),preferredStudyTimes:v.array(v.string())},handler:async(ctx,a)=>{const userId=await uid(ctx);const old=await ctx.db.query("profiles").withIndex("by_user",q=>q.eq("userId",userId)).first();const data={userId,...a,onboardingComplete:true};if(old)await ctx.db.patch(old._id,data);else await ctx.db.insert("profiles",data)}})
export const addPlan=mutation({args:{title:v.string(),date:v.string(),duration:v.number()},handler:async(ctx,a)=>ctx.db.insert("studyPlans",{userId:await uid(ctx),...a,status:"planned"})})
export const addAssignment=mutation({args:{title:v.string(),course:v.string(),dueDate:v.string(),priority:v.union(v.literal("low"),v.literal("medium"),v.literal("high"))},handler:async(ctx,a)=>ctx.db.insert("assignments",{userId:await uid(ctx),...a,status:"todo"})})
export const setAssignmentStatus=mutation({args:{id:v.id("assignments"),status:v.union(v.literal("todo"),v.literal("doing"),v.literal("done"))},handler:async(ctx,a)=>{const u=await uid(ctx);const row=await ctx.db.get(a.id);if(!row||row.userId!==u)throw new Error("Not allowed");await ctx.db.patch(a.id,{status:a.status})}})
export const addGroup=mutation({args:{name:v.string(),subject:v.string(),description:v.string()},handler:async(ctx,a)=>{const u=await uid(ctx);return ctx.db.insert("groups",{ownerId:u,...a,members:[u]})}})
export const addScholarship=mutation({args:{title:v.string(),provider:v.string(),deadline:v.string()},handler:async(ctx,a)=>ctx.db.insert("scholarships",{userId:await uid(ctx),...a,status:"saved"})})
export const saveResource=mutation({args:{name:v.string(),type:v.string(),text:v.optional(v.string()),fileId:v.optional(v.string())},handler:async(ctx,a)=>ctx.db.insert("resources",{userId:await uid(ctx),...a,createdAt:Date.now()})})
export const myCourses=query({args:{},handler:async(ctx)=>{const u=await uid(ctx);return ctx.db.query("courses").withIndex("by_user",q=>q.eq("userId",u)).order("desc").take(100)}})
export const addCourse=mutation({args:{name:v.string(),discipline:v.string(),provider:v.string(),mode:v.string(),duration:v.string(),reason:v.optional(v.string())},handler:async(ctx,a)=>{const u=await uid(ctx);const existing=await ctx.db.query("courses").withIndex("by_user",q=>q.eq("userId",u)).filter(q=>q.eq(q.field("name"),a.name)).first();if(existing)return existing._id;return ctx.db.insert("courses",{userId:u,...a,addedAt:Date.now()})}})
export const removeCourse=mutation({args:{id:v.id("courses")},handler:async(ctx,a)=>{const u=await uid(ctx);const row=await ctx.db.get(a.id);if(!row||row.userId!==u)throw new Error("Not allowed");await ctx.db.delete(a.id)}})
export const upsertProgress=mutation({args:{subject:v.string(),minutes:v.number(),mastery:v.number()},handler:async(ctx,a)=>{const u=await uid(ctx);const old=await ctx.db.query("progress").withIndex("by_user",q=>q.eq("userId",u)).filter(q=>q.eq(q.field("subject"),a.subject)).first();if(old)await ctx.db.patch(old._id,{minutes:a.minutes,mastery:a.mastery,updatedAt:Date.now()});else await ctx.db.insert("progress",{userId:u,...a,updatedAt:Date.now()})}})